quarkus:
  native:
    resources:
      includes: META-INF/services/org.slf4j.spi.SLF4JServiceProvider
    additional-build-args:
      - "-Dorg.jboss.logging.provider=slf4j"

  log:
    level: INFO
    category:
      "com.testing":
        level: DEBUG

  test:
    native-image-profile: test
